# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rthebaud <rthebaud@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/06/03 15:20:52 by rthebaud          #+#    #+#              #
#    Updated: 2014/06/10 18:32:38 by noumazza         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILES=\
main\
debug_printing\
matrix_funcs\
matrix_funcs_2\
math_funcs\
camera\
mouse_functions\
load_mesh\
load_texture\
lodepng\
get_shader\
particles\
skybox\
draw_map\
vectors\
load_scene\
load_map\
